### ISSUE TITLE
Docker Registry Container

### ISSUE THREAD

**Issue by VertigoRay** [warpnet/salt-lint#144]
Before I go re-creating the wheel, I noticed that you have a [Dockerfile](https://github.com/warpnet/salt-lint/blob/master/docker/Dockerfile), but I'm not finding an image on docker hub. I even did a quick check [under what I assume is your user](https://hub.docker.com/u/warpnet).

If this docker image is already available publicly, can you please direct me to it? If not, would you mind just linking some auto-container creation for commits to master? Otherwise, I'll go through the process of rolling my own using your code, which seems silly.

**Comment by roaldnefs** [comment]
Unfortunately the username `warpnet` on Docker Hub isn't registered by us. I've just setup the automated build on my personal profile [roaldnefs/salt-lint](https://hub.docker.com/repository/docker/roaldnefs/salt-lint).

The `Dockerfile` isn't fully tested and might require some tweaking.  If you have any feedback or questions, please let us know!

**Note:** the currently released Docker image contains the `v0.2.0` release.

**Comment by jbouter** [comment]
I've opened a call at Dockerhub to re-claim the unused username Warpnet, but I am yet to hear from them. I'll ask them again and see if this time around they're willing to reply.

**Comment by jbouter** [comment]
The Docker container has been [released to dockerhub](https://hub.docker.com/r/warpnetbv/salt-lint). Builds will now occur automatically on version releases, and when pushed to develop and master.
