### ISSUE TITLE
Add option to disable the rule with comment 

### ISSUE THREAD

**Issue by vveliev-tc** [warpnet/salt-lint#285]
**Is your feature request related to a problem? Please describe.**
Yes, when yousing salt lint, I'm not able to diable specific rule in a single file 

**Describe the solution you'd like**

Similar to other lints I would like to have option to disable rule per line and per file

```
  #salt-lint disable rule: 213, 204
  cmd.wait:
    - cwd: /usr/local
```

**Describe alternatives you've considered**

disabling rule for the project 

**Additional context**

similar options available in other lints https://yamllint.readthedocs.io/en/stable/disable_with_comments.html

**Comment by brokoli18** [comment]
It seems you can already do this: https://salt-lint.readthedocs.io/en/latest/rules/

Example:
```
 - source: salt://{{unspaced_var}}/example  # noqa: 206
```

**Comment by roaldnefs** [comment]
You can already ignore a specific rule by adding `# noqa [rule_id]` at the end of the line as explained by @brokoli18.
