### ISSUE TITLE
"global" config file option  `~/.salt-lint` or `~/.config/.salt-lint` or XDG_whatever?

### ISSUE THREAD

**Issue by mdschmitt** [warpnet/salt-lint#310]
**Is your feature request related to a problem? Please describe.**
I'd really like to have a "main" salt-lint config file for ignoring, say, rule 204 but it looks to me like it's hard-set to the current directory.  Can you make it so that it defaults to ~/.config/.salt-lint or something similar if the local one isn't found?

**Describe the solution you'd like**
If there's no
```bash
$(pwd)/.salt-lint
```
then look for
```bash
$XDG_CONFIG/.salt-lint
```
or `~/.salt-lint` and source that if it exists.

**Describe alternatives you've considered**
n/a

**Additional context**
https://github.com/warpnet/salt-lint/blob/main/saltlint/config.py#L21 looks to be the place?

**Comment by roaldnefs** [comment]
Thanks @mdschmitt for your feature request. Unfortunately we won't be introducing global configuration options. You can specify you own configuration file using the `-c` argument.
