### ISSUE TITLE
Feature Request: Check virt state deprecation

### ISSUE THREAD

**Issue by jbouter** [warpnet/salt-lint#39]
### Preface
Kindly use the [check for state.cmd deprecation](https://github.com/roaldnefs/salt-lint/pull/37) as an example of adding a check. #37 has to be merged first.

### Description

Add the possibility to check for deprecation within the [virt state](https://docs.saltstack.com/en/latest/ref/states/all/salt.states.virt.html)

The following modules have been deprecated:
* `reverted` (since _version 2016.3.0_)
* `saved` (since _version 2016.3.0_)
* `unpowered` (since _version 2016.3.0_)

The following options have been deprecated:
* `virt.running:image` (since _version 2019.2.0_)

The following options should be used:
* `reverted` => has no replacement
* `virt.running:image` => `virt.running:disks:image`
* `saved` => `snapshot()`
* `unpowered` => `stopped`

Example(s) of an **improperly** configured state:
`Reverted`:
```code
domain_name:
    virt.reverted:
        - cleanup: True
```
The `reverted` module can no longer be used.

`saved`:
```code
domain_name:
  virt.saved:
    - suffix: periodic
```
The `saved` module can no longer be used. It requires you to use the [snapshot](https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.virt.html#salt.modules.virt.snapshot) module

`unpowered`:
```code
domain_name:
  virt.unpowered
```
The `unpowered` module can no longer be used. Use the `virt.stopped` state

`virt.running:image`:
```code
domain_name:
  virt.running:
    - image: /path/to/image
```

An example of **properly** configured state:

`stopped` (instead of `unpowered`):
```code
domain_name:
  virt.stopped
```

`virt.running`:
```code
domain_name:
  virt.running:
    - disks:
      - image: /path/to/image
```

### Fix requirements
A fix for this issue should (at least):
* Notify the user of using a deprecated option
* Notify the user since what version the option will be or has been deprecated
* A suggestion on what option to replace it with
* Contain unit tests for the check

**Comment by roaldnefs** [comment]
Closed in favour of #204
