### ISSUE TITLE
Feature Request: Check cmd state deprecation

### ISSUE THREAD

**Issue by jbouter** [warpnet/salt-lint#40]
### Preface
Kindly use the [check for state.cmd deprecation](https://github.com/roaldnefs/salt-lint/pull/37) as an example of adding a check. #37 has to be merged first.

### Description

Add the possibility to check for deprecation within the [cmd state](https://docs.saltstack.com/en/latest/ref/states/all/salt.states.cmd.html)

The following options have been deprecated:
* `cmd.run:quiet` (since _version 2014.1.0_)

The following options should be used:
* `cmd.run:output_loglevel: quiet`

Example(s) of an **improperly** configured state:
```code
getpip:
  cmd.run:
    - name: /usr/bin/python /usr/local/sbin/get-pip.py
    - unless: which pip
    - require:
      - pkg: python
      - file: /usr/local/sbin/get-pip.py
    - reload_modules: True
    - quiet
```

An example of **properly** configured state:
```code
getpip:
  cmd.run:
    - name: /usr/bin/python /usr/local/sbin/get-pip.py
    - unless: which pip
    - require:
      - pkg: python
      - file: /usr/local/sbin/get-pip.py
    - reload_modules: True
    - output_loglevel: quiet
```

### Fix requirements
A fix for this issue should (at least):
* Notify the user of using a deprecated option
* Notify the user since what version the option will be or has been deprecated
* A suggestion on what option to replace it with
* Contain unit tests for the check

**Comment by kyentei** [comment]
As this check has been deprecated since 2014, we might want to consider not implementing this check.

**Comment by jbouter** [comment]
Another check to add would be `cmd.wait`, as `cmd.run` should be used together with `onchanges`.

**Comment by jbouter** [comment]
After a long wait, here's the regex that'll match properly:

```code
^\s{2}cmd\.run:(?:\n.+)+\n^\s{4}- quiet$
```

Tested against the following states, of which only the first should fail:

```code
getpip:
  cmd.run:
    - nas
    - name: /usr/bin/python /usr/local/sbin/get-pip.py
    - unless: which pip
    - require:
      - pkg: python
      - file: /usr/local/sbin/get-pip.py
    - qaas
    - reload_modules: True
    - test
    - quiet
    - mopper
      - quiet
    - more

getpip:
  cmd.wait:
	- name: test
    - quiet
    

getpip:
  cmd.run:
    - name: /usr/bin/python /usr/local/sbin/get-pip.py
    - unless: which pip
    - require:
      - pkg: python
      - file: /usr/local/sbin/get-pip.py
    - reload_modules: True
    - output_loglevel: quiet test
    - more output
```

See it in action here: https://regex101.com/r/D6SFFH/2

**Comment by jbouter** [comment]
> Another check to add would be `cmd.wait`, as `cmd.run` should be used together with `onchanges`.

A regex to match against `cmd.wait`:

```code
^\s{2}cmd\.wait:(\s+)?$
```

See it in action here: https://regex101.com/r/qXdwDr/1
