### ISSUE TITLE
Feature Request: Check lxc state deprecation

### ISSUE THREAD

**Issue by jbouter** [warpnet/salt-lint#41]
### Preface
Kindly use the [check for state.cmd deprecation](https://github.com/roaldnefs/salt-lint/pull/37) as an example of adding a check. #37 has to be merged first.

### Description

Add the possibility to check for deprecation within the [lxc state](https://docs.saltstack.com/en/latest/ref/states/all/salt.states.lxc.html)

The following options have been deprecated:
* `edited_conf` (since _version 2015.5.0_)
* `set_pass` (since _version 2015.5.0_)

The following options should be used:
_There are no alternatives. These options should simply not be used._

### Fix requirements
A fix for this issue should (at least):
* Notify the user of using a deprecated option
* Notify the user since what version the option will be or has been deprecated
* Contain unit tests for the check

**Comment by kyentei** [comment]
As these options have been deprecated since 2015, we might want to consider not implementing this check.

**Comment by roaldnefs** [comment]
Closed in favour of #204
