### ISSUE TITLE
Feature Request: Check elasticsearch_index_template state deprecation

### ISSUE THREAD

**Issue by jbouter** [warpnet/salt-lint#43]
### Preface
Kindly use the [check for state.cmd deprecation](https://github.com/roaldnefs/salt-lint/pull/37) as an example of adding a check. #37 has to be merged first.

### Description

Add the possibility to check for deprecation within the [elasticsearch_index state](https://docs.saltstack.com/en/latest/ref/states/all/salt.states.elasticsearch_index_template.html)

The following state have been deprecated:
* `elasticsearch_index_template` (since _version 2017.7.0_)

The following state should be used:
* `elasticsearch`

Example(s) of an **improperly** configured state:
```code
mytestindex2_template:
  elasticsearch_index_template.present:
    - definition:
        template: logstash-*
        order: 1
        settings:
          number_of_shards: 1
```

Example(s) of **properly** configured state:
```code
mytestindex2_template:
  elasticsearch.index_template_present:
    - definition:
        template: logstash-*
        order: 1
        settings:
          number_of_shards: 1
```

### Fix requirements
A fix for this issue should (at least):
* Notify the user of using a deprecated option
* Notify the user since what version the option will be or has been deprecated
* A suggestion on what option to replace it with
* Contain unit tests for the check

**Comment by roaldnefs** [comment]
Closed in favour of #204
