### ISSUE TITLE
Feature Request: Check rabbitmq_vhost state deprecation

### ISSUE THREAD

**Issue by jbouter** [warpnet/salt-lint#44]
### Preface
Kindly use the [check for state.cmd deprecation](https://github.com/roaldnefs/salt-lint/pull/37) as an example of adding a check. #37 has to be merged first.

### Description

Add the possibility to check for deprecation within the [rabbitmq_vhost state](https://docs.saltstack.com/en/latest/ref/states/all/salt.states.rabbitmq_vhost.html)

The following options have been deprecated:
* `user` (since _version 2017.7.0_)
* `owner` (since _version 2017.7.0_)
* `conf` (since _version 2017.7.0_)
* `write` (since _version 2017.7.0_)
* `read` (since _version 2017.7.0_)
* `runas` (both in `absent` and `present`, since _version 2017.7.0_)

The following state should be used:
_There are no given alternatives_

Example(s) of an **improperly** configured state:
_present_:
```code
virtual_host:
  rabbitmq_vhost.present:
    - name: virtual_host
    - user: rabbit_user
    - owner: rabbit_user
    - conf: .*
    - write: .*
    - read: .*
    - runas: root
```

_absent_:
```code
virtual_host:
  rabbitmq_vhost.absent:
    - name: virtual_host
    - runas: root
```
Example(s) of **properly** configured state:
_present_:
```code
virtual_host:
  rabbitmq_vhost.present:
    - name: virtual_host
```
_absent_:
```code
virtual_host:
  rabbitmq_vhost.absent:
    - name: virtual_host
```

### Fix requirements
A fix for this issue should (at least):
* Notify the user of using a deprecated option
* Notify the user since what version the option will be or has been deprecated
* A suggestion on what option to replace it with
* Contain unit tests for the check

**Comment by roaldnefs** [comment]
Closed in favour of #204
