### ISSUE TITLE
Feature Request: ignore rules per file 

### ISSUE THREAD

**Issue by roaldnefs** [warpnet/salt-lint#48]
## Preface

As @myii  suggests on [Slack](https://saltstackcommunity.slack.com/archives/C7LG8SV54/p1570869075011200), it would be useful to have to option to ignore rules per file:
> Having the ability to ignore rules per file would be really useful.  We're using that with yamllint.

> So here's a sample configuration:
> ```
> ---
> # Extend the `default` configuration provided by `yamllint`
> extends: default
> 
> # Files to ignore completely
> # 1. All YAML files under directory `node_modules/`, introduced during the Travis run
> # 2. Any SLS files under directory `test/`, which are actually state files
> # 3. Any YAML files under directory `.kitchen/`, introduced during local testing
> ignore: |
>   node_modules/
>   test/**/states/**/*.sls
>   .kitchen/
> 
> rules:
>   commas:
>     # Allow separation between commas to achieve tabular layout under `platforms`
>     ignore: |
>       ssf/defaults.yaml
>       ssf/formulas.yaml
> ```

## Description

Add to option to ignore rules per file (_using the `.salt-lint` configuration file_) like `yamllint` is doing.

**Comment by myii** [comment]
@roaldnefs If the `yamllint` format doesn't suit you, have a look at how Flake8 does it as well.
