### ISSUE TITLE
Ensure `exclude_paths` works even if files are provided on the command line

### ISSUE THREAD

**Issue by myii** [warpnet/salt-lint#72]
Based upon this configuration in the [`php-formula`](https://github.com/saltstack-formulas/php-formula/blob/8aee949cab703e4d989c20c000a628bfbf1c6fcb/.salt-lint#L4-L6):

```yaml
exclude_paths:
  # Save time spent checking files by avoiding the deprecated `ng/` directory
  - php/ng/
```

I've found that there is still a significant delay when `salt-lint` is supplied the files under this directory via. the command line:

```bash
$ php-formula$ git ls-files | grep php/ng/ | grep '\.sls$\|\.jinja$\|\.j2$\|\.tmpl$' | xargs -I {} salt-lint {}
```

The delay in this case is an extra 2 minutes during our Travis run (3 minutes for the `php-formula` compared to 1 minute for the other formulas).

---

Taking an example from `yamllint`.  Assuming there's a violation in `openvpn/defaults.yaml`:

```bash
openvpn-formula$ yamllint -s openvpn/defaults.yaml 
openvpn/defaults.yaml
  19:16     warning  too few spaces before comment  (comments)
```

If the file is ignored in the config:

```yaml
ignore: |
  openvpn/defaults.yaml
```

Then it will not run a check for it:

```bash
openvpn-formula$ yamllint -s openvpn/defaults.yaml 
```

---

The idea is for `salt-lint` to skip these files, _in all cases_, even if they are specified on the command line.

**Comment by matthijswendelaar** [comment]
@myii `salt-lint` already skips these files even though they are provided on the command line.

The current command:
```
git ls-files | grep php/ng/ | grep '\.sls$\|\.jinja$\|\.j2$\|\.tmpl$' | xargs -I {} salt-lint {}
```

Takes around 17 seconds to finish
```
15.06s user 1.65s system 99% cpu 16.723 total
```

Improving the command:
```
git ls-files | grep php/ng/ | grep '\.sls$\|\.jinja$\|\.j2$\|\.tmpl$' | xargs salt-lint
```

Takes around 0.2 seconds to finish
```
0.16s user 0.02s system 98% cpu 0.180 total
```

So it looks likes the command that you are using is causing the delay.
This is because with the first command, `salt-lint` is called for every file that exists.
If there are 100 files in the directory, `salt-lint` will be called a 100 times with 1 argument.

The second command is slightly different. It calls `salt-lint` once, with all the files as arguments.

**Comment by myii** [comment]
Good catch @matthijswendelaar, I'll check this out.  This invocation was shared, probably a remnant from a previous linter:

* https://github.com/lukaszraczylo/salt-lint#running-within-git-repo-with-its-git-files-only

**Comment by matthijswendelaar** [comment]
If it solves the problem, let me know.

**Comment by myii** [comment]
Will do, if all is OK, I'll close this issue as well.  Thanks again.

**Comment by myii** [comment]
@matthijswendelaar Checked this while reviewing #90, everything appears fine, thanks.  I'm closing this issue.

CC: @sblaisot -- you probably want to update your `salt-lint` invocation as well.
