### ISSUE TITLE
salt-lint crash when piped and having non-beakable space in outputted line

### ISSUE THREAD

**Issue by sblaisot** [warpnet/salt-lint#74]
I just encountered the following:

```
Traceback (most recent call last):
  File "/home/sblaisot/projets/salt/salt-2017.7.5-python2/bin/salt-lint", line 11, in <module>
    sys.exit(run())
  File "/home/sblaisot/projets/salt/salt-2017.7.5-python2/local/lib/python2.7/site-packages/saltlint/cli.py", line 102, in run
    print(formatter.format(match, config.colored))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xa0' in position 187: ordinal not in range(128)
```

Not sure now what triggers the problem. I'm inestigating.

It's probably due to a bad character in the sls file + salt-lint output piped to something else which disables pretty color. Not seen it with direct output without pipe.

Will add additionnal information here as soon as I can reproduce it consistently.

**Comment by sblaisot** [comment]
Fun fact:

```
$ salt-lint file.sls  # no problem
$ salt-lint --nocolor file.sls  # no problem
$ salt-lint file.sls | cat  # problem
```

**Comment by sblaisot** [comment]
I reproduced the problem with this sample state:

```
{%- set environment = salt['pillar.get']("environment", "production") %}

config-file:
    file.managed:
      - name: /path/to/config.file
      - user: root
      - group: root
      - mode: "0644"
      - source: salt://formula/files/config-{{ environment }}
```

there should be a strange character like a non-breakable space in `{{ environment }}`. Maybe we can add a test on such strange characters?

```
$ salt-lint test.sls 
[206] Jinja variables should have spaces before and after: {{ var_name }}
test.sls:9
      - source: salt://formula/files/config-{{ environment }}

$ salt-lint test.sls | cat
Traceback (most recent call last):
  File "/home/sblaisot/projets/salt/salt-2017.7.5-python2/bin/salt-lint", line 11, in <module>
    sys.exit(run())
  File "/home/sblaisot/projets/salt/salt-2017.7.5-python2/local/lib/python2.7/site-packages/saltlint/cli.py", line 102, in run
    print(formatter.format(match, config.colored))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xa0' in position 129: ordinal not in range(128)
```

**Comment by sblaisot** [comment]
Finally got it
![image](https://user-images.githubusercontent.com/2768193/67370694-6d987000-f57b-11e9-82f4-16b87274a4d6.png)

it's a non-breakable space (C2A0)
![image](https://user-images.githubusercontent.com/2768193/67370833-b2240b80-f57b-11e9-9a15-b3798c33359b.png)

**Comment by roaldnefs** [comment]
Thanks @sblaisot for the detailed bug report!

Adding a rule for such characters is actually a great idea, it will reduces the time having to spend on searching for an invisible bug. In addition to adding a new rule we also have to make sure that `salt-lint` is able to output the line without raising a `UnicodeEncodeError`.

**Comment by roaldnefs** [comment]
@sblaisot, the solution I suggested seems to break the output in Python 3... The new solution in #84  will wrap `sys.stdout` in a object that automatically encodes an unicode string into utf-8, in Python 2 only.

For more information see: #84.
