### ISSUE TITLE
Accept files through stdin

### ISSUE THREAD

**Issue by jbouter** [warpnet/salt-lint#79]
Since #77 has been merged, we have a Dockerfile ready to be built and deployed to Docker Hub.  However, not in all CI cases a repository is made available inside the running container. Thus, it would be nice to allow reading files through stdin.

Example:
```bash
salt-lint < file.sls
```

Docker example:
```bash
docker run --rm -i warpnet/salt-lint < file.sls
```

**Comment by arjenzijlstra** [comment]
This would also simplify the implementation of [SublimeLinter-salt-lint](https://github.com/warpnet/SublimeLinter-salt-lint) even more!
