### ISSUE TITLE
Documentation: Add overview of available salt-lint plug-ins

### ISSUE THREAD

**Issue by roaldnefs** [warpnet/salt-lint#97]
Add an overview of all the available `salt-lint` plugins for the different editors to the documentation. This will make it easier to start using `salt-lint`.

### Overview of plug-ins
- **vscode:** https://github.com/warpnet/vscode-salt-lint
- **sublime:** https://github.com/warpnet/SublimeLinter-salt-lint

**Comment by jbouter** [comment]
This issue will be resolved with the next release.
