### ISSUE TITLE
Ability to return non zero exit code

### ISSUE THREAD

**Issue by dawidmalina** [warpnet/salt-lint#99]
Ability to return non zero exit code if at least one of the rule will fail. This will allow us to use salt-lint during CI pipeline validation.

**Comment by roaldnefs** [comment]
@dawidmalina, if you run `salt-lint` from the command line it already returns a non-zero exit code when one or more rules fail. The snippet responsible for this:

https://github.com/warpnet/salt-lint/blob/25e582b8b25455ba7262a0ccbf259a4c64c98c4b/saltlint/__main__.py#L13

**Comment by dawidmalina** [comment]
Yes, you are right. Thank for quick feedback.
